version: '3.8'

services:
  app:
    container_name: Car_rent_app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

  postgres:
    container_name: DB_Postgres
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5431:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: DB_Redis
    image: redis:7-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: